### ISSUE TITLE
snake that bites its own tail : grimd -update

### ISSUE THREAD

**Issue by jorisd** [looterz/grimd#1]
Hi,

Thanks for creating grimd !
A little bit of context, here's my setup : 
a linux raspi with golang 1.6.2 : 

**BIND9**:
- bind9 DNS server listening on 0.0.0.0:53, that is authoritative on a private domain name (lan domain).
- bind9 configured to use grimd (127.0.0.1:54) as the sole forwarders for anything else

**GRIMD** : 
- grimd configured on 0.0.0.0:54 and forwards everything to 8.8.8.8.

**resolv.conf**
it is set to query 127.0.0.1 (bind9)

**The problem** : 
When I start `grimd -update`, it tries to lookup blacklists and so it makes DNS request to my bind9, which in turn tries to forward grimd's DNS requests to grimd. 

Since grimd is starting but not fully started, it fails. The snake bites its own tail.

Would it be possible to configure grimd to perform DNS requests on startup to 8.8.8.8 instead of 127.0.0.1 ?

Thanks

**Comment by looterz** [comment]
Thanks for the report! This should be fixed as of 8f9343cfaca405a6ebc7c0a1ad2d93101530ab4a

**Comment by jorisd** [comment]
Perfect, it works ! :+1:

**Comment by Ira1123** [comment]
Hi mistr looterz do you have a skype adress or a mail? I need to talk with you.

**Comment by Ira1123** [comment]
?

**Comment by looterz** [comment]
@Ira1123 you can direct-message me on twitter at https://twitter.com/looter__
