### ISSUE TITLE
Easylist compatibility

### ISSUE THREAD

**Issue by SR-G** [looterz/grimd#11]
As far as i can tell, grimd seems to not be compatible with easylist (https://easylist.to/easylist/easylist.txt)

So i suppose i could probably have an external curl operation with a few sed/grep to clean those lists before starting grimd, but wouldn't it be better to have to grimd work out-of-the box with that configuration ?

**Comment by looterz** [comment]
The format easylist is using is not supported by grimd currently, it can only accepts domain names as its a dns ad blocker. It looks like this list was formatted for browser extensions that block ads and have access to page content.
