### ISSUE TITLE
no work resolve host domain

### ISSUE THREAD

**Issue by myxalov** [looterz/grimd#13]
Hi! 
a linux gentoo with golang v1.7.3, grimd v1.0.2

The default configuration file.
After some time, no longer be given zone.
Here he writes in debug mode:

`[GIN-debug] Listening and serving HTTP on 127.0.0.1:8080`
`start tcp listener on 0.0.0.0:53`
`server.go:45: start udp listener on 0.0.0.0:53`
`updater.go:76: fetching source http://xxx.xxx.xxx.xxx/domain-abuse.txt`
` updater.go:92: loading blocked domains from 1 locations...`
`updater.go:121: 29857 domains loaded from sources`
` handler.go:112: ya.ru IN A didn't hit cache`
`handler.go:192: ya.ru not found in blocklist`
`resolver.go:61: ya.ru resolv on 8.8.8.8:53 (udp)`
`handler.go:240: insert ya.ru IN A into cache`

over time, domain it's not resolve :

`handler.go:128: ya.ru IN A hit cache`
`handler.go:84: 192.168.1.10 lookup　ya.ru IN A`
`handler.go:90: Found ToggleName! (cache-stav01.cdn.yandex.net)`
`activation.go:42: Toggle is too close: wait 10 seconds`
`handler.go:84: 192.168.1.10 lookup　yandex.ru IN A`
`handler.go:90: Found ToggleName! (cache-stav01.cdn.yandex.net)`
`activation.go:42: Toggle is too close: wait 10 seconds`
`handler.go:84: 192.168.1.10 lookup　yandex.ru IN A`
`handler.go:96: Grimd Activated`
`handler.go:128: yandex.ru IN A hit cache`
`handler.go:84: 192.168.1.10 lookup　yandex.ru IN A`
`handler.go:90: Found ToggleName! (cache-stav01.cdn.yandex.net)`
`handler.go:98: Grimd Deactivated`
`handler.go:128: sitecheck2.opera.com IN A hit cache`
`handler.go:84: 192.168.1.10 lookup　yandex.ru IN A`
`handler.go:90: Found ToggleName! (export.yandex.ru)`
`activation.go:42: Toggle is too close: wait 10 seconds`
what could be the problem?
that can then be added to the configuration?
Thank you!

**Comment by emdioh** [comment]
Uhm it looks like it's finding the string that toggles grimd on and off in the queries. 
What did you put for togglename in the configuration? If you didn't put anything ("") , maybe it's a bug that I've created: try to put something like togglename="_@_" that should never occur in a dns name: it should fix the issue. 
I'll have a look as soon as I get home.

**Comment by emdioh** [comment]
I confirm that this behaviour is a defect introduced by pull request [#12](https://github.com/looterz/grimd/pull/12) I'll propose a fix soon.

**Comment by looterz** [comment]
Fixed by #14.

**Comment by myxalov** [comment]
Also Grimd didn't work with national domains (etc. on russian - дом.рф). Will you fix it?
