### ISSUE TITLE
blocklist didn't refreshed with "-update"

### ISSUE THREAD

**Issue by myxalov** [looterz/grimd#17]
With command "Grimd -update" blocklist didn't refreshed.
Log:
`root@www-srv:/opt/go# ./bin/grimd -update`
`grimd v1.0.2`
`2016/12/13 09:34:24 listen tcp 127.0.0.1:8085: bind: address already in use`

**Comment by looterz** [comment]
You have to run grimd with -update without another instance already running, or else you'll get port binding conflicts and grimd will close.
