### ISSUE TITLE
Would it be possible to integrate my DRBL library with grimd?

### ISSUE THREAD

**Issue by elico** [looterz/grimd#26]
I wrote this library:
https://github.com/elico/drbl-peer

and it has an option to check a hostname against a specific blacklist server which uses wither dns or http interface.
I am using it with squid and I noticed that I can integrate it with your service easily just adding couple cli config parameters.
I can code the integration of my library, would you accept a PR or a patch that will add support for my library?
The main thing is that the DRBL service can be updated on the fly without any need to reload the any file from any server but will add a rtt addition if the service sits far in the network layer.

**Comment by elico** [comment]
@looterz Eventually I forked the code and added couple new things like cache disabling options and drbl-peer support at: https://github.com/elico/grimd

**Comment by looterz** [comment]
@elico Would you be able to submit a pull request with your changes to the dev branch? I am preparing that branch for release/merge soon so its a good place for new features.

**Comment by elico** [comment]
@looterz I did changed a lot of things and I can try to make a PR but I am not sure how smooth it will be.

**Comment by elico** [comment]
PR https://github.com/looterz/grimd/pull/28
Let me know if something is missing or not.

**Comment by looterz** [comment]
I will be removing the dev branch as it is out of date now, and I had issues getting Rice to work recently. Merged your PR.

**Comment by elico** [comment]
@looterz Thanks.
