### ISSUE TITLE
When a cached record is served it being served with static ttl

### ISSUE THREAD

**Issue by elico** [looterz/grimd#27]
I ran a simple dns lookup and the cache is served from cache but with the same ttl which the original request was responded.
Ie 3600 seconds stays and will not reduce to lower.

**Comment by looterz** [comment]
I don't know much about recommended TTL for DNS records, but I have seen 1 hour or 3600 seconds recommended for A records. What do you think grimd should do with cached records TTL?

**Comment by elico** [comment]
@looterz it should be able to store the query response TTL and respond with a relational TTL to the response.
For example if the original TTL is 3600 and the record exists since 18:00:00 then in the response at 18:01:00 the TTL should be 3540 in the response and not statically 3600 if it's in the cache.
This is a basic way of handling cached cache responses, these have "age" and every response should be served with the age.
Try to run "dig @8.8.8.8 ngtech.co.il" and you will see that it's changing while the authoritative server will always respond with a static ttl, _**but grimd is not an authoritative DNS server**_ but a proxy with caching and there for should obey a caching proxy way of handling queries and responses.

**Comment by ryancdotorg** [comment]
When `grimd` adds a DNS message to it's cache, it should:

1. loop through all answers in the message, and take the smallest ttl value (do not assume they are all the same)
2. compare that with the expires setting, and use that instead if it is smaller

The expire value for the cache `Mesg` object should be the current time plus however many seconds the smallest value found in items 1 and 2 above.

When responding from cache, `grimd` should again loop through all the answers in the message, rewriting them to be the expiration time minus the current time.

A few examples, all assuming `grimd` has the `expires` option set to 300:

* A response is received with a ttl of 55 seconds - looking up the name again 5 seconds later should give a ttl of 50 seconds. In another 50 seconds, it should expire from the cache

* A response is received with a ttl for 876 seconds - the ttl should be clamped to 300 seconds and returned. Looking it up again 60 seconds later should get a ttl of 240 seconds.

This is standard DNS caching behavior.

**Comment by ryancdotorg** [comment]
If someone can explain to how to look at the ttl on the answers, I can have a shot at this.

**Comment by elico** [comment]
@ryancdotorg I want to assist you but I am working on couple things so try to bump this later and I will try to respond.
.. Sorry

**Comment by emdioh** [comment]
#37 should fix this

**Comment by emdioh** [comment]
@looterz I think that you can close this
