### ISSUE TITLE
Daemonize

### ISSUE THREAD

**Issue by mischapeters** [looterz/grimd#3]
Hi,

Is there a way to daemonize the process, besides just adding &.

Mischa

**Comment by looterz** [comment]
It's recommended to set it up as a systemd service or init.d service, although I currently only have an example for systemd.

**Comment by mischapeters** [comment]
Understand... but I don't run Linux. ;)
If you have an rc.d example that would be great.

**Comment by looterz** [comment]
I've never worked with FreeBSD or rc.d , but here is a quick [example](https://github.com/looterz/grimd/wiki/Daemon-Scripts) I setup on a new wiki page for daemons, it probably needs some tweaking though.

**Comment by mischapeters** [comment]
Will have a look and see if the FreeBSD version can be converted to OpenBSD.

**Comment by looterz** [comment]
I should probably start compiling release binaries for FreeBSD and OpenBSD as well.

**Comment by mischapeters** [comment]
That would be great! Just build my own since I also use lego (let's encrypt in go). So wasn't an issue.
Btw... awesome daemon!

**Comment by mischapeters** [comment]
Found it ;)

**Comment by mischapeters** [comment]
If you can include this in your example page:

`#!/bin/sh
daemon="<path_to_daemon>"
rc_bg=YES

. /etc/rc.d/rc.subr

rc_reload=NO

rc_cmd $1`

**Comment by looterz** [comment]
Done, I have the more complex one and that one on there as BSD examples. Thanks!

**Comment by mischapeters** [comment]
This one is for OpenBSD

**Comment by mischapeters** [comment]
Slight modificaiton

```shell
#!/bin/sh
daemon="<path_to_daemon>"  

. /etc/rc.d/rc.subr

rc_bg=YES
rc_reload=NO

rc_cmd $1
```
