### ISSUE TITLE
Log out-put to syslog support

### ISSUE THREAD

**Issue by msenturk** [looterz/grimd#31]
First of  all its awesome tool, thanks a lot for sharing it.
I'm not sure are you still developing it actively but I got a few feature ideas for you.
Is it possible to add log to syslog feature and rotating of log file by criteria (daily, weekly or size)

**Comment by ryancdotorg** [comment]
I'd be willing to write a patch for this.

@looterz are you okay with the configuration being something simple like `log = "syslog"` or would you prefer a different option?

**Comment by looterz** [comment]
@ryancdotorg That works for me.

**Comment by ryancdotorg** [comment]
Great. I have some code already running that takes `log = "syslog"`, I'll clean it up a bit and get a pull request to you as soon as I can - probably tomorrow.
