### ISSUE TITLE
bootstrap dns server setting

### ISSUE THREAD

**Issue by wen-long** [looterz/grimd#33]
when grimd is used as system dns server,after system boot,grimd auto starts and download blocklists,but system dns is grimd itself,this makes a deadlock.

maybe there should be a configuration set the bootstrap dns server for resolve those domains in blocklists

**Comment by emdioh** [comment]
What did you set as nameservers in the configuration?
Grimd should forward the requests to those servers.

**Comment by emdioh** [comment]
Oh, I see. Thanks for explaining.

**Comment by emdioh** [comment]
I tried to repro this locally by setting grimd as the system dns and then starting it up, but it worked ok. It looks like the issue was addressed in [issue 1](https://github.com/looterz/grimd/issues/1) by 8f9343c

**Comment by wen-long** [comment]
I tried several times and find no bug.
Maybe I have some fault in my OS settings,no relevant with grimd.
I'm going to close this issue.
