### ISSUE TITLE
No recursion?

### ISSUE THREAD

**Issue by nicolas314** [looterz/grimd#6]
Hey looterz,
Thanks for writing this! I was looking for a replacement to pi-hole and grimd seems to fit the bill perfectly. I installed grimd on a RPi and declared it as primary DNS for my network (Google DNS being secondary) but unfortunately when I run a DNS query from the local network, grimd is systematically bypassed. 'nslookup' reports:
  ;; Got recursion not available from 192.168.x.x, trying next server
Is there anything that can be done about this? Forgive my ignorance about DNS issues.
Cheers
Nicolas

**Comment by looterz** [comment]
What output do you get when using dig rather than nslookup, and does the name resolving still work despite the error?

**Comment by nicolas314** [comment]
dig works fine: returns 0.0.0.0 as expected for a blocked domain.
I am trying this from an OSX machine: nslookup and host just bypass grimd and skip to the next defined DNS server, yielding the domain's true IP address. FWIW: firefox also skips grimd, but Chrome stays on grimd's answer (0.0.0.0). Seems there might be different ways of requesting DNS information on OSX.
Hope that helps!

**Comment by nicolas314** [comment]
Scratch what I just said: Firefox was stuck on a cached DNS entry. These things are hard to refresh with certainty :-) Killing FF and asking OSX to clean the DNS cache now shows blocked domains as 0.0.0.0. Seems other applications on OSX are fine with grimd. As for our CLI friends host, dig, and nslookup, their man pages on OSX mention that:

_Mac OS X NOTICE
       The dig command does not use the host name and address resolution or the DNS query routing mechanisms used by other processes running on Mac OS X.  The results of name or address queries printed by dig may differ from those found by other processes that use the Mac OS X native name and address resolution mechanisms.  The results of DNS queries may also differ from queries that use the Mac OS X DNS routing library._

So I have no idea what DNS recursion really means to those tools on OSX, but grimd does not seem to be an issue. It would be cool to understand for completeness sake, but certainly not an issue with grimd. You can definitely close this issue as you see fit.
