### ISSUE TITLE
Setup instructions for local desktop, local server

### ISSUE THREAD

**Issue by ghost** [looterz/grimd#61]
at the moment there is basic docs in the wiki for digital ocean.

what about if you want to run on your laptop Or on a raspberry pi on your home network ?
would be really nice if there was info on this.
- down to the point of explaining that you have to change the DNS resolver in your router etc

**Comment by elico** [comment]
Seems out of  scope for the project.
Can be closed to my understanding.

**Comment by looterz** [comment]
This is a bit out of scope, but if anyone would like to contribute to the wiki feel free.
