### ISSUE TITLE
Grimd + dnsmasq backend

### ISSUE THREAD

**Issue by combro2k** [looterz/grimd#64]
Hi,

I am trying to forward DNS queries to a local DNSmasq server running on port 1053 (non standard), to support for instance address=/combro2k/172.32.0.2 
If I add the entry like this into grimd.toml:

> nameservers = ["127.0.0.1:1053", "8.8.8.8:53", "8.8.4.4:53"]

And I do a lookup on the grimd server: 
> host combro2k 172.32.0.1
I got NXDOMAIN 

However if I do 
>  dig @127.0.0.1 -p 1053 combro2k 
I got the right reply.

So it looks like he doesn't call 127.0.0.1:1053 while it is being bound by dnsmasq and works directly.

Do I miss something?

**Comment by combro2k** [comment]
Found it .. 

It's due DoH was used, and it didn't use regular DNS lookup as fallback:

https://github.com/looterz/grimd/blob/master/resolver.go#L39

**Comment by combro2k** [comment]
I tackled it by using dnsmasq as master DNS and use server=127.0.0.1#1053 grimd  (localhosthost:1053) as local resolver for now.

**Comment by lpar** [comment]
Given that grimd has caching, what's the use case for running both dnsmasq and grimd?

**Comment by combro2k** [comment]
I use dnsmasq for custom DNS entries like:

address=/combro2k/172.32.0.2

It was in the OP ;-)

**Comment by lpar** [comment]
Hmm, pity grimd doesn't seem to use the IP addresses from the blocklist files, or else you could just have a blocklist file of

`172.32.0.2 combro2k`

Still, custom entries in `hosts` will still work even with grimd as DNS server. Or you could do what I do and use zeroconf for local network hostnames.

**Comment by combro2k** [comment]
I use it is a DNS server on a VPN server.
My 'services' are containerized in Docker, so it will be a challenge to get that working the easy way I think.
But will look into it later to see if I can use it that way. The suggestion of blocklist maybe will work, gonna check that out.
