### ISSUE TITLE
Can I define custom domains on my lan using grimd?

### ISSUE THREAD

**Issue by quaintdev** [looterz/grimd#78]
I would love to assign custom domains to devices using grimd but I am not sure if it is even possible. 

I tried defining domains in /etc/hosts file but it seems to have no effect. Any suggestions?

**Comment by looterz** [comment]
I believe you can, using the customdnsrecords config entry, more information is available in #68

**Comment by quaintdev** [comment]
Do you have any plans to support configuration  changes over REST api? I needed ability to add custom dns records, block websites from the mobile client that I am building.
