### ISSUE TITLE
Block via http api does not persist

### ISSUE THREAD

**Issue by quaintdev** [looterz/grimd#82]
If any website is blocked via http api, it remains blocked until grimd restarts. One has to block website again after restart.

Currently only way to block website permanently seems to be blacklist parameter in toml. Am I missing something? Any suggestions?

**Comment by looterz** [comment]
We should setup a custom blocklist managed by the HTTP API to solve this issue.

**Comment by quaintdev** [comment]
I have implemented this change and it is working form me as expected. Here is the [commit](https://github.com/quaintdev/grimd/commit/794afaed117d76d201b6cb32f88fb51825a07ac1).

I will raise pull request if this works for you.

**Comment by looterz** [comment]
Added in #83
