### ISSUE TITLE
[Improve] Update project ignore list and document configuration

### ISSUE THREAD

**Issue by soulteary** [looterz/grimd#93]
Hello maintainer 👋  @looterz 

I try to build the project locally and everything works fine, but I found two small problems:

1. After building the `grimd` and running the program, some files will be generated, which are not in the ignore list. In order to avoid introducing these files by mistake in the subsequent development process, I recommend updating the ignore list.

2. The configuration content in the project document is inconsistent with the content generated by the current program, so when it is used directly, the program will prompt like this "please update your config".

I will submit a PR fix for these two issues later, looking forward to responses from community users and maintainers, thank you.

PR:
https://github.com/looterz/grimd/pull/94

**Comment by looterz** [comment]
Thanks, good catch
