### ISSUE TITLE
[Fix] allow the project to complete the build in the docker

### ISSUE THREAD

**Issue by soulteary** [looterz/grimd#96]
Hello maintainer 👋 @looterz 

The dockerfile used by the current project needs to be used with the built binary.

If we wanted to use containers for multi-architecture builds, it would get complicated.

So I tried submitting a PR and building the program entirely inside the container.

In addition, I also use UPX to compress the program. Compared with the past, the image size of grimd will be reduced by nearly 40%, and the running and distribution speed will also become faster.

```bash
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX 3.96        Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 23rd 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   8503296 ->   3253452   38.26%   linux/amd64   grimd.minify

Packed 1 file.
```

Please review the code, if you have any questions, welcome to discuss in the issue, looking forward to your opinion

https://github.com/looterz/grimd/pull/95

**Comment by looterz** [comment]
Looks good to me, sometimes packed binaries can trigger warnings but I think we'll be okay using UPX

**Comment by looterz** [comment]
Looks like this may be [incompatible with how goreleaser expects things to work](https://goreleaser.com/customization/docker/#how-it-works) when it builds an image, you can see goreleaser failing when building from the Dockerfile [here](https://github.com/looterz/grimd/runs/5606080097?check_suite_focus=true). Will take some more investigation to figure out how to get this compatible with goreleaser, let me know if you have any ideas.

**Comment by soulteary** [comment]
Thanks for the feedback! @looterz 

Before the merge, I couldn't observe the `error` because I couldn't trigger the release, sorry :( ...

In order to ensure the continuous update of the project, we should probably restore the Dockerfile first.

I'm not sure, if future projects are willing to use multi-CPU architecture and standardized builds in docker?

If we consider starting now, maybe we can **temporarily** allow two sets of dockerfiles to appear in the project, one for goreleaser and the other to solve the above problems. And at the right point, we will use a standard multi-container architecture build in CI, instead of goreleaser?

I'm not sure how to do better, would like to hear your suggestions and views. :D

**Comment by looterz** [comment]
@soulteary I was thinking the same thing, just having a separate Dockerfile for the goreleaser pipeline, seems like the easiest solution for now.

**Comment by soulteary** [comment]
I made a small adjustment, please help me see if it fits when you have time. https://github.com/looterz/grimd/pull/101/files

This change still needs to be merged before it can be verified. 😅 @looterz
