### ISSUE TITLE
[Feat] Automatically replace the default listening address in the docker with `0.0.0.0`

### ISSUE THREAD

**Issue by soulteary** [looterz/grimd#98]
Hello maintainer 👋 @looterz 

In the default ReadMe document, I see that to run the program in a Docker, and to use the API properly, the default configuration needs to be adjusted. like this:

> For Mac docker set 'api = "0.0.0.0:8080"' instead of 'api = "127.0.0.1:8080"'.

Maybe we can make it simpler and let the application listen to 0.0.0.0 by default in the container to reduce the user's modification cost.

PR: https://github.com/looterz/grimd/pull/97

**Comment by looterz** [comment]
Thanks, best to handle stuff like that in code instead of needing anyone to check documentation
