### ISSUE TITLE
[Feat] Built-in management interface

### ISSUE THREAD

**Issue by soulteary** [looterz/grimd#99]
hello maintainer 👋  @looterz 

I tried using reaper with grimd and it worked fine.

https://github.com/looterz/reaper

But using two projects at the same time can be a bit complicated at deployment or startup time.

I have an idea, if you agree, I'll simply tweak the build, add steps to get the reaper interface, and then build reaper into grimd.

I can also add a simple user authentication feature to this interface if necessary.

Looking forward to hearing your views.

**Comment by looterz** [comment]
I really like that idea, it's been a long time coming and something I wanted to do years ago, the current separation of the projects isn't ideal.

**Comment by soulteary** [comment]
I can try to make a demo.

For more ready-made examples, please refer to the docker-flare project or the docker-flame project.

- https://github.com/soulteary/docker-flare
- https://github.com/soulteary/docker-flame

Sorry that the description languages ​​of these two projects are not in English, but it should have little effect. You can use docker run directly to verify and experience.

My imaginary result is that we can have an "AIO" , a good product out of the box, the user can enable or disable the interface or API with a parameter as someone like.

If you think this way works, I will try it. Looking forward to hearing your views.

**Comment by soulteary** [comment]
There is a choice here, we may need to discuss whether the future grimd project will be a **pure** golang project, and whether the project will consider including front-end code (eg: javascript).

- If keeping it a pure standalone golang project, then I would use **git submodule** or download the github project **release zipball** to integrate the interface.
- If you consider simple maintenance, we may try to integrate the front-end interface into this project, which may lower the integration and development threshold for other users.

How to choose, you need to make a judgment, I will quickly implement the demo after you confirm it. @looterz 🍻

**Comment by looterz** [comment]
> There is a choice here, we may need to discuss whether the future grimd project will be a **pure** golang project, and whether the project will consider including front-end code (eg: javascript).
> 
>     * If keeping it a pure standalone golang project, then I would use **git submodule** or download the github project **release zipball** to integrate the interface.
> 
>     * If you consider simple maintenance, we may try to integrate the front-end interface into this project, which may lower the integration and development threshold for other users.
> 
> 
> How to choose, you need to make a judgment, I will quickly implement the demo after you confirm it. @looterz 🍻

Personally like the idea of a git submodule, easy enough to implement but still has a separation of concerns between the web management interface and the grimd project itself.

**Comment by soulteary** [comment]
OK, then let's move in this direction first and make a try.

I will provide a demo later, let's try it together.

**Comment by soulteary** [comment]
@looterz welcome to review the code, and use docker for early trial.

https://github.com/looterz/grimd/pull/102

As before, GitHub actions require you to merge code to be able to test.

**Comment by looterz** [comment]
Looks great, testing out a merge

**Comment by soulteary** [comment]
Then this issue can be closed, and the next step is to optimize the integrated functions.
